### ISSUE TITLE
timeout with reqHistoricalDataAsync

### ISSUE THREAD

**Issue by helhadry** [ib-api-reloaded/ib_async#73]
Hello,

I'm facing a weird behavior in my script when I call the reqHistoricalDataAsync function in the main thread it returns data very quickly (0.3 seconds) but calling the same function with the same inputs in a thread take exactly 60 seconds (when I checked this function in the package I found out that the default timeout is also 60 seconds so I believe it comes from it) my question how does the function wait to timeout mentioned to return data in a thread and not in the main thread:

`async def get_historical_data(self, contract, end_date_time, duration, bar_size="1 min", what_to_show="TRADES"):
        return await self.ib_client.reqHistoricalDataAsync(
            contract,
            endDateTime=end_date_time,
            durationStr=duration,
            barSizeSetting=bar_size,
            whatToShow=what_to_show,
            useRTH=True,
        )
`
below is the call from a thread:
`bars = asyncio.run(
                            self.get_historical_data(
                                contract=position["contract"],
                                end_date_time=f"{opening_range_end.strftime('%Y%m%d %H:%M:%S')} {self.timezone_code}",
                                duration=f"{position['opening_range_minutes'] * 60} S",
                                bar_size="1 min",
                                what_to_show="TRADES",
                            )
                        )`

could you please help me understand this and how to fix it?

Thanks.

**Comment by mattsta** [comment]
One potential source of "nothing happens until the timeout:" when some of the IBKR APIs receive bad inputs, they return out-of-band error messages (check the log messages) but _no return value_.

So often we end up seeing things like "Error: contract id invalid" as an immediate status update in the logs, then your program will just freeze until the return fails to complete.

The best guard against it is to lower the timeout using `async.wait_for(thing, timeout=seconds)` to run your own faster error checking 🤷‍♂️

Longer term we _may_ be able to find a more stable way to bind error messages to currently running requests, so if we get an error status when a request is active, it could potentially stop the request early instead of waiting for the timeout.
