### ISSUE TITLE
Getting timeout error. Please help

### ISSUE THREAD

**Issue by jaxai4life** [ib-api-reloaded/ib_async#88]
My code was working fine until this Friday but I am getting timeout error since this evening when ES futures opened. I am just trying to get market data. I contacted IB and they said the ib_async may need some changes. Am using the same code since past several weeks. 

reqHistoricalData: Timeout for Contract(secType='FUT', conId=495512557, symbol='ES', lastTradeDateOrContractMonth='20241220', multiplier='50', exchange='CME', currency='USD', localSymbol='ESZ4', tradingClass='ES')
Error 366, reqId 2223: No historical data query found for ticker id:2223, contract: Contract(secType='FUT', conId=495512557, symbol='ES', lastTradeDateOrContractMonth='20241220', multiplier='50', exchange='CME', currency='USD', localSymbol='ESZ4', tradingClass='ES')

self.bars_day = await self.ib.reqHistoricalDataAsync(
            contract=self.contract,
            endDateTime="",
            barSizeSetting=config.bar_size_day,
            whatToShow="TRADES",
            durationStr="1 D",
            useRTH=0,
            keepUpToDate=True,
            timeout=120,
        )

**Comment by jaxai4life** [comment]
I just had to restart my TWS. Its working now.

**Comment by mattsta** [comment]
yeah, the IBKR APIs are actually many backend services on their system.

You can have account data working, but historical data failing because their historical data service is offline temporarily. There are also times when contract lookup or order previews are offline but other services work.

Especially trying to use services after hours, over weekends, or within 1-2 hours of weekly market open, sometimes not all services are available, but IBKR doesn't have a status page showing which services are currently working (all we can see are service timeouts when a request fails).

One thing you can do is shorten your timeout here to 5-20 seconds because historical data events like those are fairly quick to work (when they do work).
