### ISSUE TITLE
Downloading option chains with reqContractDetails

### ISSUE THREAD

**Issue by stevegee58** [ib-api-reloaded/ib_async#95]
I'm able to download option chains for SPX (index) and stocks like IBM but when I try SPY or QQQ it hangs TWS

Code example:

ib = IB()
ib.connect('127.0.0.1', 7496, clientId=1)
option_contract = Option('SPX', '', 0, '', 'SMART', '', '')
details = ib.reqContractDetails(option_contract)

**Comment by mattsta** [comment]
Yeah, it's easy to hang/break the API if you don't give it dates because IBKR will attempt to return every strike for every date for the next 5 years which is probably 5,000 to 10,000 results.

Also make sure you manually increase the java memory size for TWS or your gateway to a minimum of 6 GB and more if you're doing large data fetches (and also disable the "expose entire trading schedule to API" config option). When the gateway runs out of memory processing large results, it just hangs and stops returning anything until you restart it.

Also see the note at the end of https://interactivebrokers.github.io/tws-api/contract_details.html

**Comment by stevegee58** [comment]
Thanks, increasing the memory size to 6 GB fixed it.  I'm still confused because the SPX chain has more than 2x the number of entries as SPY, yet SPY is the one that gave me problems.

I have an existing C++ application using a fork of [JanBoonen/TwsApiCpp](https://github.com/JanBoonen/TwsApiCpp) that already worked fine without TWS hangs (i.e. downloading SPX and SPY chains).  I'm trying to transition my application to Python and I'm in the prototyping stage right now.
